# ************************************************************
# Sequel Pro SQL dump
# Version 4541
#
# http://www.sequelpro.com/
# https://github.com/sequelpro/sequelpro
#
# Host: 127.0.0.1 (MySQL 5.5.5-10.4.11-MariaDB)
# Database: dynamic_form
# Generation Time: 2020-04-29 10:08:12 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table form_descriptions
# ------------------------------------------------------------

DROP TABLE IF EXISTS `form_descriptions`;

CREATE TABLE `form_descriptions` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(255) DEFAULT NULL,
  `label` varchar(255) DEFAULT NULL,
  `tranfer_rules` text DEFAULT NULL,
  `rules` text DEFAULT NULL,
  `input_type` char(32) DEFAULT NULL,
  `special_config` text DEFAULT NULL,
  `input_props` text DEFAULT NULL,
  `sort` int(11) DEFAULT NULL,
  `span` int(11) DEFAULT NULL,
  `offset` int(11) DEFAULT NULL,
  `is_new_row` tinyint(1) DEFAULT NULL,
  `form_item_layout` text DEFAULT NULL,
  `section_id` int(11) DEFAULT NULL,
  `styles` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `created_time` timestamp NULL DEFAULT NULL,
  `updated_time` timestamp NULL DEFAULT NULL,
  `deleted_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

LOCK TABLES `form_descriptions` WRITE;
/*!40000 ALTER TABLE `form_descriptions` DISABLE KEYS */;

INSERT INTO `form_descriptions` (`id`, `key`, `label`, `tranfer_rules`, `rules`, `input_type`, `special_config`, `input_props`, `sort`, `span`, `offset`, `is_new_row`, `form_item_layout`, `section_id`, `styles`, `is_active`, `created_time`, `updated_time`, `deleted_time`)
VALUES
	(1,'outpatientNO','就诊卡号',NULL,'[{\"required\": true,\"message\":\"就诊卡号是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入就诊卡号\"}',1,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',1,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(2,'name','姓名',NULL,'[{\"required\": true,\"message\":\"姓名是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入姓名\"}',2,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',1,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(3,'mobile','手机号码',NULL,'[{\"required\": true,\"message\":\"手机号码是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入手机号码\"}',3,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',1,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(4,'telephone','固定电话',NULL,'[{\"required\": true,\"message\":\"固定电话是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入固定电话\"}',4,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',1,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(5,'idType','证件类型',NULL,'[{\"required\": true,\"message\":\"证件类型是必填项\"}]','normal_select','{\"type\":\"IDCardMapping\"}','{\"placeholder\": \"请输入证件类型\"}',5,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',1,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(6,'idNO','证件号码',NULL,'[{\"required\": true,\"message\":\"证件号码是必填项\"}]','id_number_input',NULL,'{\"placeholder\": \"请输入证件号码\"}',6,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',1,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(7,'permanentResidenceAddress','户口地址',NULL,'[{\"required\": true,\"message\":\"户口地址是必填项\"}]','address',NULL,'{\"placeholder\": \"请输入户口地址\"}',16,23,0,1,'{\"labelCol\":{\"span\":2},\"wrapperCol\":{\"span\":22}}',1,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(9,'dob','出生日期',NULL,'[{\"required\": true,\"message\":\"出生日期是必填项\"}]','single_date_picker',NULL,'{\"placeholder\": \"请输入出生日期\"}',8,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',1,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(10,'nationality','国籍',NULL,'[{\"required\": true,\"message\":\"国籍是必填项\"}]','country_select',NULL,'{\"placeholder\": \"请输入国籍\"}',9,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',1,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(11,'ethnic','民族',NULL,'[{\"required\": true,\"message\":\"民族是必填项\"}]','normal_select','{\"type\":\"ethnicMapping\", \"showSearch\":true}','{\"placeholder\": \"请输入民族\"}',12,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',1,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(12,'occupation','职业',NULL,'[{\"required\": true,\"message\":\"职业是必填项\"}]','normal_select','{\"type\":\"jobMapping\"}','{\"placeholder\": \"请输入职业\"}',13,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',1,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(13,'maritalStatus','婚姻状况',NULL,'[{\"required\": true,\"message\":\"婚姻状况是必填项\"}]','normal_select','{\"type\":\"maritalMapping\"}','{\"placeholder\": \"请输入婚姻状况\"}',14,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',1,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(14,'certificationNO','准生证号',NULL,'[{\"required\": true,\"message\":\"准生证号是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入准生证号\"}',15,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',1,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(16,'partnerName','姓名',NULL,'[{\"required\": true,\"message\":\"姓名是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入姓名\"}',1,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',2,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(17,'partnerOutpatientNO','门诊号',NULL,'[{\"required\": true,\"message\":\"门诊号是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入门诊号\"}',3,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',2,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(18,'partnerIdType','证件类型',NULL,'[{\"required\": true,\"message\":\"证件类型是必填项\"}]','normal_select','{\"type\":\"IDCardMapping\"}','{\"placeholder\": \"请输入证件类型\"}',4,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',2,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(19,'partnerIdNO','证件号码',NULL,'[{\"required\": true,\"message\":\"证件号码是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入证件号码\"}',5,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',2,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(20,'partnerAge','年龄',NULL,'[{\"required\": true,\"message\":\"年龄是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入年龄\"}',6,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',2,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(21,'partnerNationality','国籍',NULL,'[{\"required\": true,\"message\":\"国籍是必填项\"}]','country_select',NULL,'{\"placeholder\": \"请输入国籍\"}',7,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',2,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(22,'partnerNativeplace','籍贯',NULL,'[{\"required\": true,\"message\":\"籍贯是必填项\"}]','normal_select','{\"type\":\"provinceMapping\", \"showSearch\":true}','{\"placeholder\": \"请输入籍贯\"}',8,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',2,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(23,'partnerEthnic','民族',NULL,'[{\"required\": true,\"message\":\"民族是必填项\"}]','normal_select','{\"type\":\"ethnicMapping\", \"showSearch\":true}','{\"placeholder\": \"请输入民族\"}',9,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',2,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(24,'partnerOccupation','职业',NULL,'[{\"required\": true,\"message\":\"职业是必填项\"}]','normal_select','{\"type\":\"jobMapping\"}','{\"placeholder\": \"请输入职业\"}',10,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',2,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(25,'partnerProfileSmoke','吸烟',NULL,'[{\"required\": true,\"message\":\"吸烟是必填项\"}]','radio_with_input_number','{\"radioKey\": \"smoke\",\"inputKey\": \"smokeNote\",\"labelBefore\": \"\",\"labelAfter\": \"根\",\"yes\":{\"title\":\"是\",\"value\": true}, \"no\":{\"title\":\"否\",\"value\": false}}','{\"placeholder\": \"请输入吸烟\"}',11,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',2,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(26,'partnerProfileAlcohol','饮酒',NULL,'[{\"required\": true,\"message\":\"饮酒是必填项\"}]','radio_with_input_number','{\"radioKey\": \"alcohol\",\"inputKey\": \"alcoholNote\",\"labelBefore\": \"\",\"labelAfter\": \"ml\",\"yes\":{\"title\":\"是\",\"value\": true}, \"no\":{\"title\":\"否\",\"value\": false}}','{\"placeholder\": \"请输入饮酒\"}',12,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',2,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(27,'partnerProfileDisease','疾病史',NULL,'[{\"required\": true,\"message\":\"疾病史是必填项\"}]','disease_select','{\"type\":\"string\",\"options\":[{\"value\":\"hypertension\",\"label\":\"高血压\"},{\"value\":\"nephropathy\",\"label\":\"肾病\"},{\"value\":\"respiratoryDisease\",\"label\":\"呼吸系统疾病\"},{\"value\":\"gastroDisease\",\"label\":\"胃病\"},{\"value\":\"hepaticDisease\",\"label\":\"肝病\"},{\"value\":\"epilepsy\",\"label\":\"癫痫\"},{\"value\":\"cardiacDisease\",\"label\":\"心脏病\"},{\"value\":\"endocrineDisease\",\"label\":\"内分泌病\"},{\"value\":\"thyroidDisease\",\"label\":\"甲状腺\"},{\"value\":\"hematopathy\",\"label\":\"血液病\"},{\"value\":\"mentalDisease\",\"label\":\"心理疾病\"},{\"value\":\"diabetes\",\"label\":\"糖尿病\"},{\"value\":\"other\",\"label\":\"其它\"}]}','{\"placeholder\": \"请输入疾病史\"}',13,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',2,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(33,'partnerMobile','手机号码',NULL,'[{\"required\": true,\"message\":\"手机号码是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入手机号码\"}',2,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',2,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(60,'nativeplace','籍贯',NULL,'[{\"required\": true,\"message\":\"籍贯是必填项\"}]','normal_select','{\"type\":\"provinceMapping\", \"showSearch\":true}','{\"placeholder\": \"请输入籍贯\"}',10,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',1,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(61,'age','年龄',NULL,'[{\"required\": true,\"message\":\"年龄是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入年龄\"}',11,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',1,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(62,'validateDate','建档日期',NULL,'[{\"required\": true,\"message\":\"建档日期是必填项\"}]','single_date_picker',NULL,'{\"placeholder\": \"请输入建档日期\"}',1,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(63,'checkupNO','建档号',NULL,'[{\"required\": true,\"message\":\"建档号是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入建档号\"}',2,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(64,'lmp','末次月经',NULL,'[{\"required\": true,\"message\":\"末次月经是必填项\"}]','single_date_picker',NULL,'{\"placeholder\": \"请输入末次月经\"}',3,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(65,'edd','预产期-日期',NULL,'[{\"required\": true,\"message\":\"预产期-日期是必填项\"}]','single_date_picker',NULL,'{\"placeholder\": \"请输入预产期-日期\"}',4,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(66,'sureEdd','预产期-B超',NULL,'[{\"required\": true,\"message\":\"预产期-B超是必填项\"}]','single_date_picker',NULL,'{\"placeholder\": \"请输入预产期-B超\"}',5,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(67,'personalProfilePreWeight','孕前体重(kg)',NULL,'[{\"required\": true,\"message\":\"孕前体重(kg)是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入孕前体重(kg)\"}',6,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(68,'personalProfileBMI','BMI',NULL,'[{\"required\": true,\"message\":\"BMI是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入BMI\"}',8,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(69,'personalProfilePreHeight','孕前身高(cm)',NULL,'[{\"required\": true,\"message\":\"孕前身高(cm)是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入孕前身高(cm)\"}',7,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(70,'systolicPressure','收缩压(mmHg)',NULL,'[{\"required\": true,\"message\":\"收缩压(mmHg)是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入收缩压(mmHg)\"}',9,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,0,'2020-04-16 16:07:00',NULL,NULL),
	(71,'diastolicPressure','舒张压(mmHg)',NULL,'[{\"required\": true,\"message\":\"舒张压(mmHg)是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入舒张压(mmHg)\"}',10,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,0,'2020-04-16 16:07:00',NULL,NULL),
	(72,'pulse','脉搏(次/分)',NULL,'[{\"required\": true,\"message\":\"脉搏(次/分)是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入脉搏(次/分)\"}',11,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,0,'2020-04-16 16:07:00',NULL,NULL),
	(73,'menstrualHistoryMenarche','初潮(岁)',NULL,'[{\"required\": true,\"message\":\"初潮(岁)是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入初潮(岁)\"}',12,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(74,'menstrualHistoryMenstrualCycle','月经周期',NULL,'[{\"required\": true,\"message\":\"月经周期是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入月经周期\"}',13,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(75,'menstrualHistoryMenstrualPeriod','持续天数',NULL,'[{\"required\": true,\"message\":\"持续天数是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入持续天数\"}',14,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(76,'menstrualHistoryDysmenorrhea','痛经',NULL,'[{\"required\": true,\"message\":\"痛经是必填项\"}]','radio_with_input','{\"radioKey\": \"dysmenorrhea\",\"inputKey\": \"dysmenorrheaNote\",\"labelBefore\": \"\",\"labelAfter\": \"\",\"yes\":{\"title\":\"是\",\"value\": true}, \"no\":{\"title\":\"否\",\"value\": false}}','{\"placeholder\": \"请输入痛经\"}',15,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(77,'nearRelation','近亲结婚',NULL,'[{\"required\": true,\"message\":\"近亲结婚是必填项\"}]','pregnant_radio',NULL,'{\"placeholder\": \"请输入近亲结婚\"}',16,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(78,'maritalYears','结婚年龄',NULL,'[{\"required\": true,\"message\":\"结婚年龄是必填项\"}]','input',NULL,'{\"placeholder\": \"请输入结婚年龄\"}',17,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(79,'personalProfileSmoke','吸烟',NULL,'[{\"required\": true,\"message\":\"吸烟是必填项\"}]','radio_with_input_number','{\"radioKey\": \"smoke\",\"inputKey\": \"smokeNote\",\"labelBefore\": \"\",\"labelAfter\": \"根\",\"yes\":{\"title\":\"是\",\"value\": true}, \"no\":{\"title\":\"否\",\"value\": false}}','{\"placeholder\": \"请输入吸烟\"}',18,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(80,'personalProfileAlcohol','饮酒',NULL,'[{\"required\": true,\"message\":\"饮酒是必填项\"}]','radio_with_input_number','{\"radioKey\": \"alcohol\",\"inputKey\": \"alcoholNote\",\"labelBefore\": \"\",\"labelAfter\": \"ml\",\"yes\":{\"title\":\"是\",\"value\": true}, \"no\":{\"title\":\"否\",\"value\": false}}','{\"placeholder\": \"请输入饮酒\"}',19,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(81,'personalProfileHazardoussubstances','接触有害物质',NULL,'[{\"required\": true,\"message\":\"接触有害物质是必填项\"}]','radio_with_input','{\"radioKey\": \"hazardoussubstances\",\"inputKey\": \"hazardoussubstancesNote\",\"labelBefore\": \"\",\"labelAfter\": \"\",\"yes\":{\"title\":\"是\",\"value\": true}, \"no\":{\"title\":\"否\",\"value\": false}}','{\"placeholder\": \"请输入接触有害物质\"}',20,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(82,'personalProfileRadioactivity','接触放射性',NULL,'[{\"required\": true,\"message\":\"接触放射性是必填项\"}]','radio_with_input','{\"radioKey\": \"radioactivity\",\"inputKey\": \"radioactivityNote\",\"labelBefore\": \"\",\"labelAfter\": \"\",\"yes\":{\"title\":\"是\",\"value\": true}, \"no\":{\"title\":\"否\",\"value\": false}}','{\"placeholder\": \"请输入接触放射性\"}',21,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(83,'diseaseHistoryHypertension','高血压',NULL,'[{\"required\": true,\"message\":\"高血压是必填项\"}]','radio_with_input','{\"radioKey\": \"hypertension\",\"inputKey\": \"hypertensionNote\",\"labelBefore\": \"\",\"labelAfter\": \"\",\"yes\":{\"title\":\"是\",\"value\": true}, \"no\":{\"title\":\"否\",\"value\": false}}','{\"placeholder\": \"请输入高血压\"}',22,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(84,'diseaseHistoryDiabetes','糖尿病',NULL,'[{\"required\": true,\"message\":\"糖尿病是必填项\"}]','radio_with_input','{\"radioKey\": \"diabetes\",\"inputKey\": \"diabetesNote\",\"labelBefore\": \"\",\"labelAfter\": \"\",\"yes\":{\"title\":\"是\",\"value\": true}, \"no\":{\"title\":\"否\",\"value\": false}}','{\"placeholder\": \"请输入糖尿病\"}',23,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(85,'diseaseHistoryCardiacDisease','心脏病',NULL,'[{\"required\": true,\"message\":\"心脏病是必填项\"}]','radio_with_input','{\"radioKey\": \"cardiacDisease\",\"inputKey\": \"cardiacDiseaseNote\",\"labelBefore\": \"\",\"labelAfter\": \"\",\"yes\":{\"title\":\"是\",\"value\": true}, \"no\":{\"title\":\"否\",\"value\": false}}','{\"placeholder\": \"请输入心脏病\"}',24,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(86,'familyHistory','家族史',NULL,'[{\"required\": true,\"message\":\"家族史是必填项\"}]','disease_select','{\"type\":\"object\",\"options\":[{\"value\":\"hypertension\",\"label\":\"高血压\"},{\"value\":\"hepaticDisease\",\"label\":\"肝病\"},{\"value\":\"respiratoryDisease\",\"label\":\"呼吸系统疾病\"},{\"value\":\"gastroDisease\",\"label\":\"胃病\"},{\"value\":\"epilepsy\",\"label\":\"癫痫\"},{\"value\":\"cardiacDisease\",\"label\":\"心脏病\"},{\"value\":\"endocrineDisease\",\"label\":\"内分泌病\"},{\"value\":\"thyroidDisease\",\"label\":\"甲状腺\"},{\"value\":\"hematopathy\",\"label\":\"血液病\"},{\"value\":\"mentalDisease\",\"label\":\"心理疾病\"},{\"value\":\"diabetes\",\"label\":\"糖尿病\"},{\"value\":\"other\",\"label\":\"其它\"}]}','{\"placeholder\": \"请输入家族史\"}',25,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',3,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(90,'pregnancyHistories','',NULL,'','pregnancy_history','{\"type\":\"table\"}','{\"placeholder\": \"请输入\"}',25,24,0,0,'{\"labelCol\":{\"span\":0},\"wrapperCol\":{\"span\":24}}',4,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(91,'residenceAddress','居住地址',NULL,'[{\"required\": true,\"message\":\"居住地址是必填项\"}]','address',NULL,'{\"placeholder\": \"请输入居住地址\"}',17,23,0,1,'{\"labelCol\":{\"span\":2},\"wrapperCol\":{\"span\":22}}',1,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(92,'postpartumAddress','产休地址',NULL,'[{\"required\": true,\"message\":\"产休地址是必填项\"}]','address',NULL,'{\"placeholder\": \"请输入产休地址\"}',18,23,0,1,'{\"labelCol\":{\"span\":2},\"wrapperCol\":{\"span\":22}}',1,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(93,NULL,NULL,NULL,'[{\"required\": true,\"message\":\"null是必填项\"}]',NULL,NULL,'{\"placeholder\": \"请输入null\"}',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'2020-04-16 16:07:00',NULL,NULL),
	(94,'HIV','HIV',NULL,'[{\"required\": true,\"message\":\"HIV是必填项\"}]','checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":\"negative\",\"label\":\"阴性\",\"withInput\":false},{\"value\":\"positive\",\"label\":\"阳性\",\"withInput\":true,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}},{\"value\":\"other\",\"label\":\"其它\",\"withInput\":true}]}','{\"placeholder\": \"请输入HIV\"}',19,23,0,1,'{\"labelCol\":{\"span\":2},\"wrapperCol\":{\"span\":22}}',1,'{\"paddingLeft\":22}',0,'2020-04-16 16:07:00',NULL,NULL),
	(95,'allergy','过敏史',NULL,'[{\"required\": true,\"message\":\"过敏史是必填项\"}]','checkbox_with_input','{\"type\":\"multiple\",\"options\":[{\"value\":\"no\",\"label\":\"无\",\"withInput\":false,\"resetAll\":true},{\"value\":\"medicine\",\"label\":\"药物\",\"withInput\":true,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}},{\"value\":\"food\",\"label\":\"食物\",\"withInput\":true,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}},{\"value\":\"other\",\"label\":\"其它\",\"withInput\":true,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}}]}','{\"placeholder\": \"请输入过敏史\"}',19,23,0,1,'{\"labelCol\":{\"span\":2},\"wrapperCol\":{\"span\":22}}',1,'{\"paddingLeft\":22}',0,'2020-04-16 16:07:00',NULL,NULL),
	(96,'pregnancyEnd','妊娠终止时间',NULL,'[{\"required\": true,\"message\":\"妊娠终止时间是必填项\"}]','single_date_picker','','{\"placeholder\": \"请输入妊娠终止时间\", \"picker\":\"month\"}',1,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(97,'complicationNote','并发症',NULL,'[{\"required\": true,\"message\":\"并发症是必填项\"}]','input','','{\"placeholder\": \"请输入并发症\"}',2,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(98,'hasPregnancy','是否分娩',NULL,'[{\"required\": true,\"message\":\"是否分娩是必填项\"}]','has_pregnancy','','',3,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(99,'hospital','分娩医院',NULL,'[{\"required\": true,\"message\":\"分娩医院是必填项\"}]','input','','{\"placeholder\": \"请输入分娩医院\"}',4,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(100,'gestationalWeek','分娩孕周',NULL,'[{\"required\": true,\"message\":\"分娩孕周是必填项\"}]','input','','{\"placeholder\": \"请输入分娩孕周\"}',5,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(101,'fetalcount','胎数',NULL,'[{\"required\": true,\"message\":\"胎数是必填项\"}]','fetal_count','','{\"placeholder\": \"请输入胎数\"}',6,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(102,'deliverWay','分娩方式',NULL,'[{\"required\": true,\"message\":\"分娩方式是必填项\"}]','select_with_options','{\"type\":\"array\",\"mode\":\"single\",\"options\":[{\"value\":\"vaginalDelivery\",\"label\":\"顺产\"},{\"value\":\"cesareanSection\",\"label\":\"剖宫产\"},{\"value\":\"forceps\",\"label\":\"钳产\"},{\"value\":\"vacuumAssisted\",\"label\":\"吸引产\"},{\"value\":\"breechMidwifery\",\"label\":\"臀助产\"}]}','{\"placeholder\": \"请输入分娩方式\"}',7,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(103,'puerperalFever','产溽热',NULL,'[{\"required\": true,\"message\":\"产溽热是必填项\"}]','pregnant_radio','','{\"placeholder\": \"请输入产溽热\"}',8,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(104,'hemorrhage','产后出血',NULL,'[{\"required\": true,\"message\":\"产后出血是必填项\"}]','pregnant_radio','','{\"placeholder\": \"请输入产后出血\"}',9,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(105,'abortionWay','流产方式',NULL,'[{\"required\": true,\"message\":\"流产方式是必填项\"}]','select_with_options','{\"type\":\"array\",\"mode\":\"single\",\"options\":[{\"value\":\"medicalAbortion\",\"label\":\"药物流产\"},{\"value\":\"surgicalAbortion\",\"label\":\"手术流产\"},{\"value\":\"naturalAbortion\",\"label\":\"自然流产\"},{\"value\":\"currettage\",\"label\":\"清宫\"}]}','{\"placeholder\": \"请输入流产方式\"}',10,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(106,'badPregnancy','不良生育史',NULL,'[{\"required\": true,\"message\":\"不良生育史是必填项\"}]','select_with_options','{\"type\":\"array\",\"mode\":\"multiple\",\"options\":[{\"value\":\"inducedLabor\",\"label\":\"死产\"},{\"value\":\"fetusdeath\",\"label\":\"死胎\"},{\"value\":\"ectopicPregnancy\",\"label\":\"异位妊娠\"},{\"value\":\"hydatidMole\",\"label\":\"葡萄胎\"},{\"value\":\"multiple\",\"label\":\"多胎妊娠\"}]}','{\"placeholder\": \"请输入不良生育史\"}',11,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(107,'childDeath','新生儿当前情况',NULL,'[{\"required\": true,\"message\":\"新生儿当前情况是必填项\"}]','pregnant_radio','','{\"placeholder\": \"请输入新生儿当前情况\"}',12,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(108,'childDeathNote','死亡原因',NULL,'[{\"required\": true,\"message\":\"死亡原因是必填项\"}]','custom','','{\"placeholder\": \"请输入死亡原因\"}',13,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(109,'childGender','性别',NULL,'[{\"required\": true,\"message\":\"性别是必填项\"}]','custom','','{\"placeholder\": \"请输入性别\"}',14,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(110,'sequela','后遗症',NULL,'[{\"required\": true,\"message\":\"后遗症是必填项\"}]','custom','','{\"placeholder\": \"请输入后遗症\"}',15,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(111,'childDeformity','畸形',NULL,'[{\"required\": true,\"message\":\"畸形是必填项\"}]','custom','','{\"placeholder\": \"请输入畸形\"}',16,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(112,'neonateWeight','出生体重(kg)',NULL,'[{\"required\": true,\"message\":\"出生体重(kg)是必填项\"}]','custom','','{\"placeholder\": \"请输入出生体重(kg)\"}',17,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(113,'neonateHeight','出生身长(cm)',NULL,'[{\"required\": true,\"message\":\"出生身长(cm)是必填项\"}]','custom','','{\"placeholder\": \"请输入出生身长(cm)\"}',18,7,1,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',5,'{\"paddingLeft\":22}',1,'2020-04-16 16:07:00',NULL,NULL),
	(114,'pressure','血压',NULL,'[{\"required\": true,\"message\":\"血压是必填项\"}]','input','','{\"placeholder\": \"请输入血压\"}',4,6,0,1,'{\"labelCol\":{\"span\":16},\"wrapperCol\":{\"span\":8}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(115,'pulse','脉搏',NULL,'[{\"required\": true,\"message\":\"脉搏是必填项\"}]','input_number','','{\"placeholder\": \"请输入脉搏\"}',4,6,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(116,'height','身高',NULL,'[{\"required\": true,\"message\":\"身高是必填项\"}]','input_number','','{\"placeholder\": \"请输入身高\"}',4,6,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(117,'weight','现体重',NULL,'[{\"required\": true,\"message\":\"现体重是必填项\"}]','input_number','','{\"placeholder\": \"请输入现体重\"}',4,6,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(118,'prevWeight','孕前体重',NULL,'[{\"required\": true,\"message\":\"孕前体重是必填项\"}]','input_number','','{\"placeholder\": \"请输入孕前体重\"}',4,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(119,'prev','孕前',NULL,'[{\"required\": true,\"message\":\"孕前是必填项\"}]','input_number','','{\"placeholder\": \"请输入孕前\"}',4,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(120,'mucosa','皮肤黏膜',NULL,'[{\"required\": true,\"message\":\"皮肤黏膜是必填项\"}]','checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":\"normal\",\"label\":\"正常\",\"withInput\":false,\"span\":6,\"offset\":0},{\"value\":\"other\",\"label\":\"其他\",\"withInput\":true,\"span\":6,\"inputSpan\":11,\"offset\":1,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}}]}','{\"placeholder\": \"请输入皮肤黏膜\"}',4,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(121,'thyroid','甲状腺',NULL,'[{\"required\": true,\"message\":\"甲状腺是必填项\"}]','checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":\"normal\",\"label\":\"正常\",\"withInput\":false,\"span\":6,\"offset\":0},{\"value\":\"other\",\"label\":\"其他\",\"withInput\":true,\"span\":6,\"inputSpan\":11,\"offset\":1,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}}]}','{\"placeholder\": \"请输入甲状腺\"}',4,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(122,'breath','呼吸音',NULL,'[{\"required\": true,\"message\":\"呼吸音是必填项\"}]','checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":\"normal\",\"label\":\"清\",\"span\":6,\"offset\":0,\"withInput\":false},{\"value\":\"other\",\"label\":\"其他\",\"withInput\":true,\"span\":6,\"inputSpan\":11,\"offset\":1,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}}]}','{\"placeholder\": \"请输入呼吸音\"}',4,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(123,'rale','啰音',NULL,'[{\"required\": true,\"message\":\"啰音是必填项\"}]','checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":\"normal\",\"label\":\"无\",\"span\":6,\"offset\":0,\"withInput\":false},{\"value\":\"other\",\"label\":\"其他\",\"withInput\":true,\"span\":6,\"inputSpan\":11,\"offset\":1,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}}]}','{\"placeholder\": \"请输入啰音\"}',4,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(124,'heartRate','心率',NULL,'[{\"required\": true,\"message\":\"心率是必填项\"}]','input','','{\"placeholder\": \"请输入心率\"}',4,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(125,'heartRhythm','心律',NULL,'[{\"required\": true,\"message\":\"心律是必填项\"}]','checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":\"alignment\",\"label\":\"齐\",\"withInput\":false},{\"value\":\"noAlignment\",\"label\":\"不齐\",\"withInput\":true,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}}]}','{\"placeholder\": \"请输入心律\"}',4,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(126,'noise','杂音',NULL,'[{\"required\": true,\"message\":\"杂音是必填项\"}]','checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":\"normal\",\"label\":\"无\",\"withInput\":false},{\"value\":\"other\",\"label\":\"有\",\"withInput\":true,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}}]}','{\"placeholder\": \"请输入杂音\"}',4,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(127,'liver','肝脏',NULL,'[{\"required\": true,\"message\":\"肝脏是必填项\"}]','checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":\"normal\",\"label\":\"未触及\",\"withInput\":false},{\"value\":\"other\",\"label\":\"可触及\",\"withInput\":true,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}}]}','{\"placeholder\": \"请输入肝脏\"}',4,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(128,'spleen','脾脏',NULL,'[{\"required\": true,\"message\":\"脾脏是必填项\"}]','checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":\"normal\",\"label\":\"未触及\",\"withInput\":false},{\"value\":\"other\",\"label\":\"可触及\",\"withInput\":true,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}}]}','{\"placeholder\": \"请输入脾脏\"}',4,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(129,'percussionPain','肾区叩痛',NULL,'[{\"required\": true,\"message\":\"肾区叩痛是必填项\"}]','checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":\"normal\",\"label\":\"无\",\"withInput\":false},{\"value\":\"other\",\"label\":\"有\",\"withInput\":true,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}}]}','{\"placeholder\": \"请输入肾区叩痛\"}',4,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(130,'vertebra','脊椎',NULL,'[{\"required\": true,\"message\":\"脊椎是必填项\"}]','checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":\"normal\",\"label\":\"正常\",\"withInput\":false},{\"value\":\"other\",\"label\":\"其它\",\"withInput\":true,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}}]}','{\"placeholder\": \"请输入脊椎\"}',4,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(131,'physiologicalReflex','生理反射',NULL,'[{\"required\": true,\"message\":\"生理反射是必填项\"}]','checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":\"normal\",\"label\":\"存在\",\"withInput\":false},{\"value\":\"other\",\"label\":\"其它\",\"withInput\":true,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}}]}','{\"placeholder\": \"请输入生理反射\"}',4,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(132,'pathologicalReflex','病理反射',NULL,'[{\"required\": true,\"message\":\"病理反射是必填项\"}]','checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":\"normal\",\"label\":\"无\",\"withInput\":false},{\"value\":\"other\",\"label\":\"有\",\"withInput\":true,\"exceptionStyle\":{\"checkboxStyle\":{\"color\":\"#ff0000\"},\"inputStyle\":{\"borderColor\":\"#ff0000\"}}}]}','{\"placeholder\": \"请输入病理反射\"}',4,7,0,0,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(133,'edema','下肢水肿',NULL,'[{\"required\": true,\"message\":\"下肢水肿是必填项\"}]','checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":\"select1\",\"label\":\"-\",\"span\":2,\"offset\":0,\"withInput\":false},{\"value\":\"select2\",\"label\":\"+\",\"span\":2,\"offset\":1,\"withInput\":false},{\"value\":\"select3\",\"label\":\"+-\",\"span\":2,\"offset\":1,\"withInput\":false},{\"value\":\"select4\",\"label\":\"++\",\"span\":2,\"offset\":1,\"withInput\":true,\"inputSpan\":4},{\"value\":\"select5\",\"label\":\"+++\",\"span\":2,\"offset\":1,\"withInput\":false}]}','{\"placeholder\": \"请输入下肢水肿\"}',4,23,0,1,'{\"labelCol\":{\"span\":2},\"wrapperCol\":{\"span\":22}}',7,'{\"paddingLeft\":22}',1,'2020-04-20 17:33:28',NULL,NULL),
	(134,'others','其他',NULL,'[{\"required\": true,\"message\":\"其他是必填项\"}]','input','','{\"placeholder\": \"请输入其他\"}',4,7,0,1,'{\"labelCol\":{\"span\":8},\"wrapperCol\":{\"span\":16}}',7,'',1,'2020-04-20 17:33:28',NULL,NULL),
	(138,'laborTime','临产时间',NULL,'[{\"required\": true,\"message\":\"临产时间是必填项\"}]','single_date_picker','','{\"placeholder\":\"请输入临产时间\",\"format\":\"YYYY-MM-DD HH:mm:ss\",\"showTime\":true}',1,7,0,0,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',8,'',0,'2020-04-23 14:44:46',NULL,NULL),
	(139,'membranesrupturedtime','胎膜破裂时间','{\"type\":\"moment\",\"path\":\"membranesrupturedtime\"}','[{\"required\": true,\"message\":\"胎膜破裂时间是必填项\"}]','single_date_picker','','{\"placeholder\": \"请输入胎膜破裂时间\",\"format\":\"YYYY-MM-DD HH:mm:ss\",\"showTime\":true}',1,7,0,0,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',8,'',1,'2020-04-23 14:44:46',NULL,NULL),
	(141,'cervixdopenedtime','宫口开全时间','{\"type\":\"moment\",\"path\":\"cervixdopenedtime\"}','[{\"required\": true,\"message\":\"宫口全开时间是必填项\"}]','single_date_picker','','{\"placeholder\": \"请输入宫口全开时间\",\"format\":\"YYYY-MM-DD HH:mm:ss\",\"showTime\":true}',4,7,0,1,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',8,'',1,'2020-04-23 14:44:46',NULL,NULL),
	(142,'preamnioticfluidcharacter','破膜羊水形状','','[{\"required\": true,\"message\":\"破膜羊水是必填项\"}]','checkbox_group','{\"type\":\"single\",\"options\":[{\"value\":0,\"label\":\"清\",\"withInput\":false,\"span\":6},{\"value\":1,\"label\":\"Ⅰ°\",\"withInput\":false,\"span\":6},{\"value\":2,\"label\":\"Ⅱ°\",\"withInput\":false,\"span\":6},{\"value\":3,\"label\":\"Ⅲ°\",\"withInput\":false,\"span\":6}]}','{\"placeholder\": \"请输入破膜羊水\"}',5,7,0,0,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',8,'',1,'2020-04-23 14:44:46',NULL,NULL),
	(143,'deliverytime','胎儿娩出时间','{\"type\":\"moment\",\"path\":\"noenateRecords.0.deliverytime\"}','[{\"required\": true,\"message\":\"胎儿娩出时间是必填项\"}]','single_date_picker','','{\"placeholder\": \"请输入胎儿娩出时间\",\"format\":\"YYYY-MM-DD HH:mm:ss\",\"showTime\":true}',7,7,0,1,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',8,'',1,'2020-04-23 14:44:46',NULL,NULL),
	(144,'deliverytype','胎儿娩出方式','{\"path\":\"noenateRecords.0.deliverytype\"}','[{\"required\": true,\"message\":\"胎儿娩出方式是必填项\"}]','checkbox_group','{\"type\":\"single\",\"options\":[{\"value\":0,\"label\":\"顺产\",\"withInput\":false,\"span\":4},{\"value\":1,\"label\":\"吸引产\",\"withInput\":false,\"span\":4},{\"value\":2,\"label\":\" 臀助产 \",\"withInput\":false,\"span\":4},{\"value\":3,\"label\":\"臀牵引\",\"withInput\":false,\"span\":4},{\"value\":4,\"label\":\"钳产\",\"withInput\":false,\"span\":4},{\"value\":5,\"label\":\"剖宫产 \",\"withInput\":false,\"span\":4}]}','{\"placeholder\": \"请输入胎儿娩出方式\"}',8,14,0,0,'{\"labelCol\":{\"span\":5},\"wrapperCol\":{\"span\":19}}',8,'',1,'2020-04-23 14:44:46',NULL,NULL),
	(145,'fetalposition','胎方位','{\"path\":\"noenateRecords.0.fetalposition\"}','[{\"required\": true,\"message\":\"胎方位是必填项\"}]','normal_select','{\"type\": \"fetalpositionMapping\"}','{\"placeholder\": \"请输入胎方位\"}',9,7,0,1,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',8,'',1,'2020-04-23 14:44:46',NULL,NULL),
	(146,'placentadeliveredtime','胎盘娩出时间','{\"type\":\"moment\",\"path\":\"noenateRecords.0.placentadeliveredtime\"}','[{\"required\": true,\"message\":\"胎盘娩出时间是必填项\"}]','single_date_picker','','{\"placeholder\": \"请输入胎盘娩出时间\",\"format\":\"YYYY-MM-DD HH:mm:ss\",\"showTime\":true}',10,7,0,0,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',8,'',1,'2020-04-23 14:44:46',NULL,NULL),
	(147,'placentadeliveredtype','胎盘娩出方式','{\"type\":\"key_and_keyNote\",\"path\":\"noenateRecords.0.placentadeliveredtype\"}','[{\"required\": true,\"message\":\"胎盘娩出方式是必填项\"}]','normal_checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":0,\"label\":\"胎儿面\",\"withInput\":false,\"span\":4},{\"value\":1,\"label\":\"母体面\",\"withInput\":false,\"span\":4},{\"value\":2,\"label\":\" 自然娩出 \",\"withInput\":false,\"span\":4},{\"value\":3,\"label\":\"手取胎盘术\",\"withInput\":true,\"labelBefore\":\"原因:\",\"span\":4}]}','{\"placeholder\": \"请输入胎盘娩出方式\"}',11,14,0,1,'{\"labelCol\":{\"span\":5},\"wrapperCol\":{\"span\":19}}',8,'',1,'2020-04-23 14:44:46',NULL,NULL),
	(148,'reason','原因',NULL,'[{\"required\": true,\"message\":\"原因是必填项\"}]','input','','{\"placeholder\": \"请输入原因\"}',12,7,0,0,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',8,'',0,'2020-04-23 14:44:46',NULL,NULL),
	(149,'firststage','第一产程时间','{\"type\":\"stage\"}','[{\"required\": true,\"message\":\"产程时间是必填项\"}]','multiple_input_with_label','{\"type\":\"number\",\"options\":[{\"labelBefore\":\"\",\"labelAfter\":\"时\"},{\"labelBefore\":\"\",\"labelAfter\":\"分\"}]}','{\"min\":0}',13,7,0,1,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',8,'',1,'2020-04-23 14:44:46',NULL,NULL),
	(150,'fetusAppendages','','{\"type\":\"fetusAppendages\",\"path\":\"noenateRecords\"}','[{\"required\": true,\"message\":\"胎盘是必填项\"}]','fetus_appendages','','',4,23,0,0,'{\"labelCol\":{\"span\":2},\"wrapperCol\":{\"span\":22}}',9,'',1,'2020-04-23 14:44:49',NULL,NULL),
	(155,'perineum','会阴情况','{\"type\":\"key_and_keyNote\"}','[{\"required\": true,\"message\":\"会阴情况是必填项\"}]','normal_checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":0,\"label\":\"完整\",\"span\":3,\"withInput\":false},{\"value\":1,\"label\":\"切开\",\"withInput\":true,\"inputType\":\"checkbox\",\"inputSpan\":6,\"span\":3,\"options\":[{\"value\":2,\"label\":\"侧切\"},{\"value\":3,\"label\":\"直切\"}]},{\"value\":4,\"label\":\"破裂\",\"withInput\":true,\"inputType\":\"checkbox\",\"inputSpan\":6,\"span\":3,\"options\":[{\"value\":5,\"label\":\"Ⅰ°\"},{\"value\":6,\"label\":\"Ⅱ°\"},{\"value\":7,\"label\":\"Ⅲ°\"}]},{\"value\":8,\"label\":\"其它\",\"inputSpan\":4,\"span\":3,\"withInput\":true}]}','{\"placeholder\": \"请输入会阴\"}',4,22,0,0,'{\"labelCol\":{\"span\":3},\"wrapperCol\":{\"span\":14}}',10,'',1,'2020-04-23 14:44:51',NULL,NULL),
	(156,'perineumsuture','缝合情况','{\"type\":\"key_and_keyNote\"}','[{\"required\": true,\"message\":\"缝合情况是必填项\"}]','normal_checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":0,\"label\":\"皮内缝合\",\"span\":3,\"withInput\":false},{\"value\":1,\"label\":\"外缝\",\"inputSpan\":6,\"span\":3,\"withInput\":true,\"enterType\":\"number\",\"labelAfter\":\"针\"},{\"value\":2,\"label\":\"其它\",\"inputSpan\":6,\"span\":3,\"withInput\":true}]}','{\"placeholder\": \"请输入缝合情况\"}',4,22,0,1,'{\"labelCol\":{\"span\":3},\"wrapperCol\":{\"span\":14}}',10,'',1,'2020-04-23 14:44:51',NULL,NULL),
	(157,'cervicalaceration','宫颈裂伤','{\"type\":\"key_and_keyNote\"}','[{\"required\": true,\"message\":\"宫颈是必填项\"}]','normal_checkbox_with_input','{\"type\":\"single\",\"options\":[{\"value\":0,\"label\":\"无破\",\"span\":2,\"withInput\":false},{\"value\":1,\"label\":\"裂伤\",\"withInput\":true,\"inputType\":\"multiple_input\",\"span\":2,\"inputSpan\":18,\"options\":[{\"labelBefore\":\"部位:\",\"labelAfter\":\"点处,\"},{\"labelBefore\":\"裂伤深度:\",\"labelAfter\":\"cm,\",\"enterType\":\"number\"},{\"labelBefore\":\"其他:\"}]}]}','{\"placeholder\": \"请输入宫颈\"}',4,22,0,1,'{\"labelCol\":{\"span\":3},\"wrapperCol\":{\"span\":21}}',10,'',1,'2020-04-23 14:44:51',NULL,NULL),
	(158,'operation','所施手术',NULL,'[{\"required\": true,\"message\":\"所施手术是必填项\"}]','input','','{\"placeholder\": \"请输入所施手术\"}',4,7,0,0,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',10,'',1,'2020-04-23 14:44:51',NULL,NULL),
	(159,'operationReason','手术原因',NULL,'[{\"required\": true,\"message\":\"手术原因是必填项\"}]','input','','{\"placeholder\": \"请输入手术原因\"}',4,7,0,0,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',10,'',1,'2020-04-23 14:44:51',NULL,NULL),
	(161,'postpartumhemorrhage','分娩后2小时总出血量',NULL,'[{\"required\": true,\"message\":\"阴道分娩产后2小时总出血量是必填项\"}]','input_with_label','{\"type\":\"number\",\"labelBefore\":\"\",\"labelAfter\":\"ml\"}','{\"placeholder\": \"请输入阴道分娩产后2小时总出血量\"}',4,7,0,1,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',10,'',1,'2020-04-23 14:44:51',NULL,NULL),
	(162,'intrapartumhemorrhage','剖宫产出血量',NULL,'[{\"required\": true,\"message\":\"剖宫产出血量是必填项\"}]','input_with_label','{\"type\":\"number\",\"labelBefore\":\"\",\"labelAfter\":\"ml\"}','{\"placeholder\": \"请输入剖宫产出血量\"}',4,7,0,0,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',10,'',1,'2020-04-23 14:44:51',NULL,NULL),
	(163,'apgar','','{\"type\":\"apgar\"}','','apgar_score_input','{\"type\":\"simple\"}','{\"placeholder\": \"请输入一分钟\"}',4,23,0,1,'{\"labelCol\":{\"span\":0},\"wrapperCol\":{\"span\":24}}',11,'',1,'2020-04-23 14:44:53',NULL,NULL),
	(166,'membranesrupturedtype','胎膜破裂方式',NULL,'[{\"required\": true,\"message\":\"胎膜破裂时间是必填项\"}]','checkbox_group','{\"type\":\"single\",\"options\":[{\"value\":1,\"label\":\"自然\",\"withInput\":false,\"span\":12},{\"value\":2,\"label\":\"人工\",\"withInput\":false,\"span\":12}]}','',2,7,0,0,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',8,'',1,'2020-04-23 14:44:46',NULL,NULL),
	(167,'preamnioticfluidvolume','破膜羊水量',NULL,'[{\"required\": true,\"message\":\"破膜羊水是必填项\"}]','input_with_label','{\"type\":\"number\",\"labelBefore\":\"\",\"labelAfter\":\"ml\"}','{\"placeholder\": \"请输入破膜羊水\"}',6,7,0,0,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',8,'',1,'2020-04-23 14:44:46',NULL,NULL),
	(168,'secondstage','第二产程时间','{\"type\":\"stage\"}','[{\"required\": true,\"message\":\"产程时间是必填项\"}]','multiple_input_with_label','{\"type\":\"number\",\"options\":[{\"labelBefore\":\"\",\"labelAfter\":\"时\"},{\"labelBefore\":\"\",\"labelAfter\":\"分\"}]}','{\"min\":0}',14,7,0,0,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',8,'',1,'2020-04-23 14:44:46',NULL,NULL),
	(170,'thirdstage','第三产程时间','{\"type\":\"stage\"}','[{\"required\": true,\"message\":\"产程时间是必填项\"}]','multiple_input_with_label','{\"type\":\"number\",\"options\":[{\"labelBefore\":\"\",\"labelAfter\":\"时\"},{\"labelBefore\":\"\",\"labelAfter\":\"分\"}]}','{\"min\":0}',15,7,0,0,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',8,'',1,'2020-04-23 14:44:46',NULL,NULL),
	(171,'totalstage','总产程时间','{\"type\":\"stage\"}','[{\"required\": true,\"message\":\"产程时间是必填项\"}]','multiple_input_with_label','{\"type\":\"number\",\"options\":[{\"labelBefore\":\"\",\"labelAfter\":\"时\"},{\"labelBefore\":\"\",\"labelAfter\":\"分\"}]}','{\"min\":0}',15,7,0,1,'{\"labelCol\":{\"span\":10},\"wrapperCol\":{\"span\":14}}',8,'',1,'2020-04-23 14:44:46',NULL,NULL),
	(172,'placentaintact','胎盘完整性','{\"type\":\"key_and_keyNote\", \"path\":\"fetusAppendages.placentaintact\"}','[{\"required\": true,\"message\":\"手术原因是必填项\"}]','normal_checkbox_with_input','{\"type\":\"single\",\"options\":[{\"label\":\"完整\",\"value\":0},{\"label\":\"基本完整\",\"value\":1},{\"label\":\"不完整\",\"value\":2,\"withInput\":true,\"inputType\":\"multiple_input\",\"options\":[{\"enterType\":\"number\",\"labelBefore\":\"缺损:\"},{\"enterType\":\"number\",\"labelBefore\":\"X\"}]},{\"label\":\"粗糙面\",\"value\":3,\"withInput\":true,\"inputType\":\"multiple_input\",\"options\":[{\"enterType\":\"number\",\"labelBefore\":\"面积:\"},{\"enterType\":\"number\",\"labelBefore\":\"X\"}]}]}','{\"placeholder\": \"请输入手术原因\"}',1,23,0,0,'{\"labelCol\":{\"span\":3},\"wrapperCol\":{\"span\":21}}',12,'',1,'2020-04-23 14:44:51',NULL,NULL),
	(173,'placentasize','胎盘大小','{\"path\":\"fetusAppendages.placentasize\"}','[{\"required\": true,\"message\":\"手术原因是必填项\"}]','multiple_input_with_label','{\"type\":\"number\",\"options\":[{\"labelBefore\":\"长:\",\"labelAfter\":\"cm\"},{\"labelBefore\":\"宽:\",\"labelAfter\":\"cm\"},{\"labelBefore\":\"厚:\",\"labelAfter\":\"cm\"},{\"labelBefore\":\"重:\",\"labelAfter\":\"g\"}]}','{\"placeholder\": \"请输入手术原因\"}',2,23,0,1,'{\"labelCol\":{\"span\":3},\"wrapperCol\":{\"span\":21}}',12,'',1,'2020-04-23 14:44:51',NULL,NULL),
	(174,'insertion','胎盘附着','{\"type\":\"key_and_keyNote\",\"path\":\"fetusAppendages.insertion\"}','[{\"required\": true,\"message\":\"手术原因是必填项\"}]','select_with_input','{\"selectedValueShowInput\":1,\"options\":[{\"value\":0,\"label\":\"中央\"},{\"value\":1,\"label\":\"其它\"}]}','{\"placeholder\": \"请输入胎盘特殊情况\"}',3,23,0,1,'{\"labelCol\":{\"span\":3},\"wrapperCol\":{\"span\":5}}',12,'',1,'2020-04-23 14:44:51',NULL,NULL),
	(175,'membranesintact','胎膜完整性','{\"type\":\"key_and_keyNote\", \"path\":\"fetusAppendages.membranesintact\"}','[{\"required\": true,\"message\":\"手术原因是必填项\"}]','normal_checkbox_with_input','{\"type\":\"single\",\"options\":[{\"label\":\"完整\",\"value\":0},{\"label\":\"基本完整\",\"value\":1},{\"label\":\"不完整\",\"value\":2,\"withInput\":true,\"inputType\":\"multiple_input\",\"options\":[{\"enterType\":\"number\",\"labelBefore\":\"缺损:\"},{\"enterType\":\"number\",\"labelBefore\":\"X\"}]}]}','{\"placeholder\": \"请输入手术原因\"}',5,23,0,1,'{\"labelCol\":{\"span\":3},\"wrapperCol\":{\"span\":21}}',12,'',1,'2020-04-23 14:44:51',NULL,NULL),
	(176,'umbilicalcordlength','脐带长度','{\"path\":\"fetusAppendages.umbilicalcordlength\"}','[{\"required\": true,\"message\":\"手术原因是必填项\"}]','input_with_label','{\"type\":\"number\",\"labelAfter\":\"cm\"}','{\"placeholder\": \"请输入手术原因\"}',5,23,0,1,'{\"labelCol\":{\"span\":3},\"wrapperCol\":{\"span\":21}}',12,'',1,'2020-04-23 14:44:51',NULL,NULL),
	(177,'amnioticfluidcharacter','后羊水形状',NULL,'[{\"required\": true,\"message\":\"手术原因是必填项\"}]','checkbox_group','{\"type\":\"single\",\"options\":[{\"label\":\"清\",\"value\":0},{\"label\":\"Ⅰ°\",\"value\":1},{\"label\":\"Ⅱ°\",\"value\":2},{\"label\":\"Ⅲ°\",\"value\":3},{\"label\":\"血性\",\"value\":4}]}','{\"placeholder\": \"请输入手术原因\"}',12,23,0,1,'{\"labelCol\":{\"span\":3},\"wrapperCol\":{\"span\":21}}',8,'',1,'2020-04-23 14:44:51',NULL,NULL),
	(179,'otherNote','胎盘特殊情况','{\"path\":\"fetusAppendages.otherNote\"}','[{\"required\": true,\"message\":\"手术原因是必填项\"}]','input','','{\"placeholder\": \"请输入胎盘特殊情况\"}',4,23,0,1,'{\"labelCol\":{\"span\":3},\"wrapperCol\":{\"span\":5}}',12,'',1,'2020-04-23 14:44:51',NULL,NULL),
	(181,'umbilicalcordNote','脐带特殊情况','{\"path\":\"fetusAppendages.umbilicalcordNote\"}','[{\"required\": true,\"message\":\"手术原因是必填项\"}]','input','','{\"placeholder\": \"请输入手术原因\"}',5,23,0,1,'{\"labelCol\":{\"span\":3},\"wrapperCol\":{\"span\":5}}',12,'',1,'2020-04-23 14:44:51',NULL,NULL);

/*!40000 ALTER TABLE `form_descriptions` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table form_sections
# ------------------------------------------------------------

DROP TABLE IF EXISTS `form_sections`;

CREATE TABLE `form_sections` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `flag` varchar(255) DEFAULT NULL,
  `sort` int(11) DEFAULT NULL,
  `created_time` timestamp NULL DEFAULT NULL,
  `updated_time` timestamp NULL DEFAULT NULL,
  `deleted_time` timestamp NULL DEFAULT NULL,
  `module_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

LOCK TABLES `form_sections` WRITE;
/*!40000 ALTER TABLE `form_sections` DISABLE KEYS */;

INSERT INTO `form_sections` (`id`, `name`, `flag`, `sort`, `created_time`, `updated_time`, `deleted_time`, `module_name`)
VALUES
	(1,'孕妇基本信息','pregnantWoman',1,NULL,NULL,NULL,'pregnant'),
	(2,'丈夫基本信息','husband',2,NULL,NULL,NULL,'pregnant'),
	(3,'本次孕产信息','pregnantInfo',3,NULL,NULL,NULL,'pregnant'),
	(4,'孕产史','pregnantHistory',4,NULL,NULL,NULL,'pregnant'),
	(5,'孕产史配置','pregnantHistorySetting',1,NULL,NULL,NULL,'pregnantHistorySetting'),
	(7,'体格检查','physicalExam',1,NULL,NULL,NULL,'physicalExam'),
	(8,'分娩记录单','deliverRecords',1,NULL,NULL,NULL,'deliverForm'),
	(9,'胎儿附属物检查情况','fetusCheck',1,NULL,NULL,NULL,'deliverForm'),
	(10,'软产道检查情况','birthCanalCheck',1,NULL,NULL,NULL,'deliverForm'),
	(11,'新生儿评分(Apgar)','neonatalScore',1,NULL,NULL,NULL,'deliverForm'),
	(12,'胎儿附属物配置配置','foetalAppendage',1,NULL,NULL,NULL,'foetalAppendage');

/*!40000 ALTER TABLE `form_sections` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table users
# ------------------------------------------------------------

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
