export default {
  dataSource: [
    {
      key: '1',
      orderNumber: '1',
      submitTime: '2',
      username: '3',
      contactType: '4',
      orderMoney: '5',
      payType: '6',
      orderStatus: '待付款',
    },
    {
      key: '2',
      orderNumber: '2',
      submitTime: '2',
      username: '3',
      contactType: '4',
      orderMoney: '5',
      payType: '6',
      orderStatus: '已支付',
    },
    {
      key: '3',
      orderNumber: '3',
      submitTime: '2',
      username: '3',
      contactType: '4',
      orderMoney: '5',
      payType: '6',
      orderStatus: '使用中',
    },
    {
      key: '4',
      orderNumber: '4',
      submitTime: '2',
      username: '3',
      contactType: '4',
      orderMoney: '5',
      payType: '6',
      orderStatus: '逾期中',
    },
    {
      key: '5',
      orderNumber: '5',
      submitTime: '2',
      username: '3',
      contactType: '4',
      orderMoney: '5',
      payType: '6',
      orderStatus: '待归还',
    },
    {
      key: '6',
      orderNumber: '6',
      submitTime: '2',
      username: '3',
      contactType: '4',
      orderMoney: '5',
      payType: '6',
      orderStatus: '已完成',
    },
    {
      key: '7',
      orderNumber: '7',
      submitTime: '2',
      username: '3',
      contactType: '4',
      orderMoney: '5',
      payType: '6',
      orderStatus: '已关闭',
      createdTime: '2017-07-19 15:43:23'
    },
  ],
};
